# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='fb',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
