# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_speaker_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
