# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_auto_20170112_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='fb',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
